[package]
name = "curl"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "curl"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { version = "0.7.1", features = ["logger"] }
log = "0.4.8"

[dev-dependencies]
marine-rs-sdk-test = "0.10.0"
